// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (template_id, external_ref, payload, occurred_at)
VALUES ($1, $2, $3, $4)
RETURNING id, template_id, external_ref, payload, occurred_at, received_at
`

type CreateEventParams struct {
	TemplateID  pgtype.UUID        `json:"template_id"`
	ExternalRef *string            `json:"external_ref"`
	Payload     []byte             `json:"payload"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.TemplateID,
		arg.ExternalRef,
		arg.Payload,
		arg.OccurredAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ExternalRef,
		&i.Payload,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, template_id, external_ref, payload, occurred_at, received_at FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ExternalRef,
		&i.Payload,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, template_id, external_ref, payload, occurred_at, received_at FROM events ORDER BY received_at DESC LIMIT $1 OFFSET $2
`

type ListEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.ExternalRef,
			&i.Payload,
			&i.OccurredAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByTemplate = `-- name: ListEventsByTemplate :many
SELECT id, template_id, external_ref, payload, occurred_at, received_at FROM events WHERE template_id = $1 ORDER BY received_at DESC LIMIT $2 OFFSET $3
`

type ListEventsByTemplateParams struct {
	TemplateID pgtype.UUID `json:"template_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListEventsByTemplate(ctx context.Context, arg ListEventsByTemplateParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByTemplate, arg.TemplateID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.ExternalRef,
			&i.Payload,
			&i.OccurredAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET external_ref = $2, payload = $3, occurred_at = $4
WHERE id = $1
RETURNING id, template_id, external_ref, payload, occurred_at, received_at
`

type UpdateEventParams struct {
	ID          pgtype.UUID        `json:"id"`
	ExternalRef *string            `json:"external_ref"`
	Payload     []byte             `json:"payload"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.ExternalRef,
		arg.Payload,
		arg.OccurredAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ExternalRef,
		&i.Payload,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}
