// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          pgtype.UUID        `json:"id"`
	TemplateID  pgtype.UUID        `json:"template_id"`
	ExternalRef *string            `json:"external_ref"`
	Payload     []byte             `json:"payload"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
}

type Rule struct {
	ID         pgtype.UUID        `json:"id"`
	TemplateID pgtype.UUID        `json:"template_id"`
	Name       string             `json:"name"`
	Expression string             `json:"expression"`
	Severity   string             `json:"severity"`
	Message    string             `json:"message"`
	Priority   int32              `json:"priority"`
	Status     string             `json:"status"`
	Mode       string             `json:"mode"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Template struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Schema      []byte             `json:"schema"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
