// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRule = `-- name: CreateRule :one
INSERT INTO rules (template_id, name, expression, severity, message, priority, status, mode)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, template_id, name, expression, severity, message, priority, status, mode, created_at, updated_at
`

type CreateRuleParams struct {
	TemplateID pgtype.UUID `json:"template_id"`
	Name       string      `json:"name"`
	Expression string      `json:"expression"`
	Severity   string      `json:"severity"`
	Message    string      `json:"message"`
	Priority   int32       `json:"priority"`
	Status     string      `json:"status"`
	Mode       string      `json:"mode"`
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.TemplateID,
		arg.Name,
		arg.Expression,
		arg.Severity,
		arg.Message,
		arg.Priority,
		arg.Status,
		arg.Mode,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Expression,
		&i.Severity,
		&i.Message,
		&i.Priority,
		&i.Status,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules WHERE id = $1
`

func (q *Queries) DeleteRule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRule, id)
	return err
}

const getRule = `-- name: GetRule :one
SELECT id, template_id, name, expression, severity, message, priority, status, mode, created_at, updated_at FROM rules WHERE id = $1
`

func (q *Queries) GetRule(ctx context.Context, id pgtype.UUID) (Rule, error) {
	row := q.db.QueryRow(ctx, getRule, id)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Expression,
		&i.Severity,
		&i.Message,
		&i.Priority,
		&i.Status,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRulesByTemplate = `-- name: ListActiveRulesByTemplate :many
SELECT id, template_id, name, expression, severity, message, priority, status, mode, created_at, updated_at FROM rules WHERE template_id = $1 AND status = 'active' ORDER BY priority ASC
`

func (q *Queries) ListActiveRulesByTemplate(ctx context.Context, templateID pgtype.UUID) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listActiveRulesByTemplate, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Name,
			&i.Expression,
			&i.Severity,
			&i.Message,
			&i.Priority,
			&i.Status,
			&i.Mode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT id, template_id, name, expression, severity, message, priority, status, mode, created_at, updated_at FROM rules ORDER BY priority ASC, created_at DESC LIMIT $1 OFFSET $2
`

type ListRulesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRules(ctx context.Context, arg ListRulesParams) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listRules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Name,
			&i.Expression,
			&i.Severity,
			&i.Message,
			&i.Priority,
			&i.Status,
			&i.Mode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesByTemplate = `-- name: ListRulesByTemplate :many
SELECT id, template_id, name, expression, severity, message, priority, status, mode, created_at, updated_at FROM rules WHERE template_id = $1 ORDER BY priority ASC, created_at DESC LIMIT $2 OFFSET $3
`

type ListRulesByTemplateParams struct {
	TemplateID pgtype.UUID `json:"template_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListRulesByTemplate(ctx context.Context, arg ListRulesByTemplateParams) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listRulesByTemplate, arg.TemplateID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Name,
			&i.Expression,
			&i.Severity,
			&i.Message,
			&i.Priority,
			&i.Status,
			&i.Mode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :one
UPDATE rules
SET name = $2, expression = $3, severity = $4, message = $5,
    priority = $6, status = $7, mode = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, template_id, name, expression, severity, message, priority, status, mode, created_at, updated_at
`

type UpdateRuleParams struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	Expression string      `json:"expression"`
	Severity   string      `json:"severity"`
	Message    string      `json:"message"`
	Priority   int32       `json:"priority"`
	Status     string      `json:"status"`
	Mode       string      `json:"mode"`
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, updateRule,
		arg.ID,
		arg.Name,
		arg.Expression,
		arg.Severity,
		arg.Message,
		arg.Priority,
		arg.Status,
		arg.Mode,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Expression,
		&i.Severity,
		&i.Message,
		&i.Priority,
		&i.Status,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
