// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (slug, name, description, schema)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, description, schema, created_at, updated_at
`

type CreateTemplateParams struct {
	Slug        string  `json:"slug"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Schema      []byte  `json:"schema"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Schema,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Schema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTemplate, id)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, slug, name, description, schema, created_at, updated_at FROM templates WHERE id = $1
`

func (q *Queries) GetTemplate(ctx context.Context, id pgtype.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Schema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateBySlug = `-- name: GetTemplateBySlug :one
SELECT id, slug, name, description, schema, created_at, updated_at FROM templates WHERE slug = $1
`

func (q *Queries) GetTemplateBySlug(ctx context.Context, slug string) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateBySlug, slug)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Schema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, slug, name, description, schema, created_at, updated_at FROM templates ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListTemplatesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Schema,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET slug = $2, name = $3, description = $4, schema = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, slug, name, description, schema, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID          pgtype.UUID `json:"id"`
	Slug        string      `json:"slug"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	Schema      []byte      `json:"schema"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Schema,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Schema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
