// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateRuleRequestMode.
const (
	CreateRuleRequestModeLive   CreateRuleRequestMode = "live"
	CreateRuleRequestModeShadow CreateRuleRequestMode = "shadow"
)

// Valid indicates whether the value is a known member of the CreateRuleRequestMode enum.
func (e CreateRuleRequestMode) Valid() bool {
	switch e {
	case CreateRuleRequestModeLive:
		return true
	case CreateRuleRequestModeShadow:
		return true
	default:
		return false
	}
}

// Defines values for CreateRuleRequestSeverity.
const (
	CreateRuleRequestSeverityCritical CreateRuleRequestSeverity = "critical"
	CreateRuleRequestSeverityHigh     CreateRuleRequestSeverity = "high"
	CreateRuleRequestSeverityLow      CreateRuleRequestSeverity = "low"
	CreateRuleRequestSeverityMedium   CreateRuleRequestSeverity = "medium"
)

// Valid indicates whether the value is a known member of the CreateRuleRequestSeverity enum.
func (e CreateRuleRequestSeverity) Valid() bool {
	switch e {
	case CreateRuleRequestSeverityCritical:
		return true
	case CreateRuleRequestSeverityHigh:
		return true
	case CreateRuleRequestSeverityLow:
		return true
	case CreateRuleRequestSeverityMedium:
		return true
	default:
		return false
	}
}

// Defines values for CreateRuleRequestStatus.
const (
	CreateRuleRequestStatusActive   CreateRuleRequestStatus = "active"
	CreateRuleRequestStatusDisabled CreateRuleRequestStatus = "disabled"
	CreateRuleRequestStatusDraft    CreateRuleRequestStatus = "draft"
)

// Valid indicates whether the value is a known member of the CreateRuleRequestStatus enum.
func (e CreateRuleRequestStatus) Valid() bool {
	switch e {
	case CreateRuleRequestStatusActive:
		return true
	case CreateRuleRequestStatusDisabled:
		return true
	case CreateRuleRequestStatusDraft:
		return true
	default:
		return false
	}
}

// Defines values for RuleMode.
const (
	RuleModeLive   RuleMode = "live"
	RuleModeShadow RuleMode = "shadow"
)

// Valid indicates whether the value is a known member of the RuleMode enum.
func (e RuleMode) Valid() bool {
	switch e {
	case RuleModeLive:
		return true
	case RuleModeShadow:
		return true
	default:
		return false
	}
}

// Defines values for RuleSeverity.
const (
	RuleSeverityCritical RuleSeverity = "critical"
	RuleSeverityHigh     RuleSeverity = "high"
	RuleSeverityLow      RuleSeverity = "low"
	RuleSeverityMedium   RuleSeverity = "medium"
)

// Valid indicates whether the value is a known member of the RuleSeverity enum.
func (e RuleSeverity) Valid() bool {
	switch e {
	case RuleSeverityCritical:
		return true
	case RuleSeverityHigh:
		return true
	case RuleSeverityLow:
		return true
	case RuleSeverityMedium:
		return true
	default:
		return false
	}
}

// Defines values for RuleStatus.
const (
	RuleStatusActive   RuleStatus = "active"
	RuleStatusDisabled RuleStatus = "disabled"
	RuleStatusDraft    RuleStatus = "draft"
)

// Valid indicates whether the value is a known member of the RuleStatus enum.
func (e RuleStatus) Valid() bool {
	switch e {
	case RuleStatusActive:
		return true
	case RuleStatusDisabled:
		return true
	case RuleStatusDraft:
		return true
	default:
		return false
	}
}

// Defines values for UpdateRuleRequestMode.
const (
	Live   UpdateRuleRequestMode = "live"
	Shadow UpdateRuleRequestMode = "shadow"
)

// Valid indicates whether the value is a known member of the UpdateRuleRequestMode enum.
func (e UpdateRuleRequestMode) Valid() bool {
	switch e {
	case Live:
		return true
	case Shadow:
		return true
	default:
		return false
	}
}

// Defines values for UpdateRuleRequestSeverity.
const (
	Critical UpdateRuleRequestSeverity = "critical"
	High     UpdateRuleRequestSeverity = "high"
	Low      UpdateRuleRequestSeverity = "low"
	Medium   UpdateRuleRequestSeverity = "medium"
)

// Valid indicates whether the value is a known member of the UpdateRuleRequestSeverity enum.
func (e UpdateRuleRequestSeverity) Valid() bool {
	switch e {
	case Critical:
		return true
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for UpdateRuleRequestStatus.
const (
	UpdateRuleRequestStatusActive   UpdateRuleRequestStatus = "active"
	UpdateRuleRequestStatusDisabled UpdateRuleRequestStatus = "disabled"
	UpdateRuleRequestStatusDraft    UpdateRuleRequestStatus = "draft"
)

// Valid indicates whether the value is a known member of the UpdateRuleRequestStatus enum.
func (e UpdateRuleRequestStatus) Valid() bool {
	switch e {
	case UpdateRuleRequestStatusActive:
		return true
	case UpdateRuleRequestStatusDisabled:
		return true
	case UpdateRuleRequestStatusDraft:
		return true
	default:
		return false
	}
}

// Defines values for ListRulesParamsStatus.
const (
	ListRulesParamsStatusActive   ListRulesParamsStatus = "active"
	ListRulesParamsStatusDisabled ListRulesParamsStatus = "disabled"
	ListRulesParamsStatusDraft    ListRulesParamsStatus = "draft"
)

// Valid indicates whether the value is a known member of the ListRulesParamsStatus enum.
func (e ListRulesParamsStatus) Valid() bool {
	switch e {
	case ListRulesParamsStatusActive:
		return true
	case ListRulesParamsStatusDisabled:
		return true
	case ListRulesParamsStatusDraft:
		return true
	default:
		return false
	}
}

// CreateEventRequest defines model for CreateEventRequest.
type CreateEventRequest struct {
	ExternalRef *string                `json:"externalRef,omitempty"`
	OccurredAt  time.Time              `json:"occurredAt"`
	Payload     map[string]interface{} `json:"payload"`
	TemplateId  openapi_types.UUID     `json:"templateId"`
}

// CreateRuleRequest defines model for CreateRuleRequest.
type CreateRuleRequest struct {
	Expression string                    `json:"expression"`
	Message    *string                   `json:"message,omitempty"`
	Mode       *CreateRuleRequestMode    `json:"mode,omitempty"`
	Name       string                    `json:"name"`
	Priority   *int                      `json:"priority,omitempty"`
	Severity   CreateRuleRequestSeverity `json:"severity"`
	Status     *CreateRuleRequestStatus  `json:"status,omitempty"`
	TemplateId openapi_types.UUID        `json:"templateId"`
}

// CreateRuleRequestMode defines model for CreateRuleRequest.Mode.
type CreateRuleRequestMode string

// CreateRuleRequestSeverity defines model for CreateRuleRequest.Severity.
type CreateRuleRequestSeverity string

// CreateRuleRequestStatus defines model for CreateRuleRequest.Status.
type CreateRuleRequestStatus string

// CreateTemplateRequest defines model for CreateTemplateRequest.
type CreateTemplateRequest struct {
	Description *string                 `json:"description,omitempty"`
	Name        string                  `json:"name"`
	Schema      *map[string]interface{} `json:"schema,omitempty"`
	Slug        string                  `json:"slug"`
}

// Error defines model for Error.
type Error struct {
	Details *[]string `json:"details,omitempty"`
	Message string    `json:"message"`
}

// Event defines model for Event.
type Event struct {
	ExternalRef *string                `json:"externalRef,omitempty"`
	Id          openapi_types.UUID     `json:"id"`
	OccurredAt  time.Time              `json:"occurredAt"`
	Payload     map[string]interface{} `json:"payload"`
	ReceivedAt  time.Time              `json:"receivedAt"`
	TemplateId  openapi_types.UUID     `json:"templateId"`
}

// EventIngestionResult defines model for EventIngestionResult.
type EventIngestionResult struct {
	Alerts []FiredAlert `json:"alerts"`
	Event  Event        `json:"event"`
}

// EventList defines model for EventList.
type EventList struct {
	Data []Event `json:"data"`
}

// FiredAlert defines model for FiredAlert.
type FiredAlert struct {
	Message  string             `json:"message"`
	RuleId   openapi_types.UUID `json:"ruleId"`
	RuleName string             `json:"ruleName"`
	Severity string             `json:"severity"`
}

// Rule defines model for Rule.
type Rule struct {
	CreatedAt  time.Time          `json:"createdAt"`
	Expression string             `json:"expression"`
	Id         openapi_types.UUID `json:"id"`
	Message    string             `json:"message"`
	Mode       RuleMode           `json:"mode"`
	Name       string             `json:"name"`
	Priority   int                `json:"priority"`
	Severity   RuleSeverity       `json:"severity"`
	Status     RuleStatus         `json:"status"`
	TemplateId openapi_types.UUID `json:"templateId"`
	UpdatedAt  time.Time          `json:"updatedAt"`
}

// RuleMode defines model for Rule.Mode.
type RuleMode string

// RuleSeverity defines model for Rule.Severity.
type RuleSeverity string

// RuleStatus defines model for Rule.Status.
type RuleStatus string

// RuleList defines model for RuleList.
type RuleList struct {
	Data []Rule `json:"data"`
}

// Template defines model for Template.
type Template struct {
	CreatedAt   time.Time              `json:"createdAt"`
	Description *string                `json:"description,omitempty"`
	Id          openapi_types.UUID     `json:"id"`
	Name        string                 `json:"name"`
	Schema      map[string]interface{} `json:"schema"`
	Slug        string                 `json:"slug"`
	UpdatedAt   time.Time              `json:"updatedAt"`
}

// TemplateList defines model for TemplateList.
type TemplateList struct {
	Data  []Template `json:"data"`
	Total int        `json:"total"`
}

// UpdateEventRequest defines model for UpdateEventRequest.
type UpdateEventRequest struct {
	ExternalRef *string                `json:"externalRef,omitempty"`
	OccurredAt  time.Time              `json:"occurredAt"`
	Payload     map[string]interface{} `json:"payload"`
}

// UpdateRuleRequest defines model for UpdateRuleRequest.
type UpdateRuleRequest struct {
	Expression string                    `json:"expression"`
	Message    *string                   `json:"message,omitempty"`
	Mode       *UpdateRuleRequestMode    `json:"mode,omitempty"`
	Name       string                    `json:"name"`
	Priority   *int                      `json:"priority,omitempty"`
	Severity   UpdateRuleRequestSeverity `json:"severity"`
	Status     *UpdateRuleRequestStatus  `json:"status,omitempty"`
}

// UpdateRuleRequestMode defines model for UpdateRuleRequest.Mode.
type UpdateRuleRequestMode string

// UpdateRuleRequestSeverity defines model for UpdateRuleRequest.Severity.
type UpdateRuleRequestSeverity string

// UpdateRuleRequestStatus defines model for UpdateRuleRequest.Status.
type UpdateRuleRequestStatus string

// UpdateTemplateRequest defines model for UpdateTemplateRequest.
type UpdateTemplateRequest struct {
	Description *string                 `json:"description,omitempty"`
	Name        string                  `json:"name"`
	Schema      *map[string]interface{} `json:"schema,omitempty"`
	Slug        string                  `json:"slug"`
}

// ID defines model for ID.
type ID = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = Error

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	Limit      *Limit              `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *Offset             `form:"offset,omitempty" json:"offset,omitempty"`
	TemplateId *openapi_types.UUID `form:"template_id,omitempty" json:"template_id,omitempty"`
}

// ListRulesParams defines parameters for ListRules.
type ListRulesParams struct {
	Limit      *Limit                 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *Offset                `form:"offset,omitempty" json:"offset,omitempty"`
	TemplateId *openapi_types.UUID    `form:"template_id,omitempty" json:"template_id,omitempty"`
	Status     *ListRulesParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListRulesParamsStatus defines parameters for ListRules.
type ListRulesParamsStatus string

// ListTemplatesParams defines parameters for ListTemplates.
type ListTemplatesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = CreateEventRequest

// UpdateEventJSONRequestBody defines body for UpdateEvent for application/json ContentType.
type UpdateEventJSONRequestBody = UpdateEventRequest

// CreateRuleJSONRequestBody defines body for CreateRule for application/json ContentType.
type CreateRuleJSONRequestBody = CreateRuleRequest

// UpdateRuleJSONRequestBody defines body for UpdateRule for application/json ContentType.
type UpdateRuleJSONRequestBody = UpdateRuleRequest

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = CreateTemplateRequest

// UpdateTemplateJSONRequestBody defines body for UpdateTemplate for application/json ContentType.
type UpdateTemplateJSONRequestBody = UpdateTemplateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List events
	// (GET /events)
	ListEvents(ctx echo.Context, params ListEventsParams) error
	// Ingest an event and evaluate active rules
	// (POST /events)
	CreateEvent(ctx echo.Context) error
	// Delete an event
	// (DELETE /events/{id})
	DeleteEvent(ctx echo.Context, id ID) error
	// Get an event by ID
	// (GET /events/{id})
	GetEvent(ctx echo.Context, id ID) error
	// Update an event
	// (PUT /events/{id})
	UpdateEvent(ctx echo.Context, id ID) error
	// List rules
	// (GET /rules)
	ListRules(ctx echo.Context, params ListRulesParams) error
	// Create a rule (expression is validated before saving)
	// (POST /rules)
	CreateRule(ctx echo.Context) error
	// Delete a rule
	// (DELETE /rules/{id})
	DeleteRule(ctx echo.Context, id ID) error
	// Get a rule by ID
	// (GET /rules/{id})
	GetRule(ctx echo.Context, id ID) error
	// Update a rule (expression re-validated)
	// (PUT /rules/{id})
	UpdateRule(ctx echo.Context, id ID) error
	// List templates
	// (GET /templates)
	ListTemplates(ctx echo.Context, params ListTemplatesParams) error
	// Create a template
	// (POST /templates)
	CreateTemplate(ctx echo.Context) error
	// Delete a template
	// (DELETE /templates/{id})
	DeleteTemplate(ctx echo.Context, id ID) error
	// Get a template by ID
	// (GET /templates/{id})
	GetTemplate(ctx echo.Context, id ID) error
	// Update a template
	// (PUT /templates/{id})
	UpdateTemplate(ctx echo.Context, id ID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListEvents converts echo context to params.
func (w *ServerInterfaceWrapper) ListEvents(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "template_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "template_id", ctx.QueryParams(), &params.TemplateId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter template_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListEvents(ctx, params)
	return err
}

// CreateEvent converts echo context to params.
func (w *ServerInterfaceWrapper) CreateEvent(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateEvent(ctx)
	return err
}

// DeleteEvent converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteEvent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteEvent(ctx, id)
	return err
}

// GetEvent converts echo context to params.
func (w *ServerInterfaceWrapper) GetEvent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEvent(ctx, id)
	return err
}

// UpdateEvent converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateEvent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateEvent(ctx, id)
	return err
}

// ListRules converts echo context to params.
func (w *ServerInterfaceWrapper) ListRules(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRulesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "template_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "template_id", ctx.QueryParams(), &params.TemplateId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter template_id: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", ctx.QueryParams(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListRules(ctx, params)
	return err
}

// CreateRule converts echo context to params.
func (w *ServerInterfaceWrapper) CreateRule(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateRule(ctx)
	return err
}

// DeleteRule converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteRule(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteRule(ctx, id)
	return err
}

// GetRule converts echo context to params.
func (w *ServerInterfaceWrapper) GetRule(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetRule(ctx, id)
	return err
}

// UpdateRule converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateRule(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateRule(ctx, id)
	return err
}

// ListTemplates converts echo context to params.
func (w *ServerInterfaceWrapper) ListTemplates(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTemplatesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListTemplates(ctx, params)
	return err
}

// CreateTemplate converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTemplate(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTemplate(ctx)
	return err
}

// DeleteTemplate converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTemplate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTemplate(ctx, id)
	return err
}

// GetTemplate converts echo context to params.
func (w *ServerInterfaceWrapper) GetTemplate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTemplate(ctx, id)
	return err
}

// UpdateTemplate converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTemplate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTemplate(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/events", wrapper.ListEvents)
	router.POST(baseURL+"/events", wrapper.CreateEvent)
	router.DELETE(baseURL+"/events/:id", wrapper.DeleteEvent)
	router.GET(baseURL+"/events/:id", wrapper.GetEvent)
	router.PUT(baseURL+"/events/:id", wrapper.UpdateEvent)
	router.GET(baseURL+"/rules", wrapper.ListRules)
	router.POST(baseURL+"/rules", wrapper.CreateRule)
	router.DELETE(baseURL+"/rules/:id", wrapper.DeleteRule)
	router.GET(baseURL+"/rules/:id", wrapper.GetRule)
	router.PUT(baseURL+"/rules/:id", wrapper.UpdateRule)
	router.GET(baseURL+"/templates", wrapper.ListTemplates)
	router.POST(baseURL+"/templates", wrapper.CreateTemplate)
	router.DELETE(baseURL+"/templates/:id", wrapper.DeleteTemplate)
	router.GET(baseURL+"/templates/:id", wrapper.GetTemplate)
	router.PUT(baseURL+"/templates/:id", wrapper.UpdateTemplate)

}

type BadRequestJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type UnprocessableEntityJSONResponse Error

type ListEventsRequestObject struct {
	Params ListEventsParams
}

type ListEventsResponseObject interface {
	VisitListEventsResponse(w http.ResponseWriter) error
}

type ListEvents200JSONResponse EventList

func (response ListEvents200JSONResponse) VisitListEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListEvents500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListEvents500JSONResponse) VisitListEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateEventRequestObject struct {
	Body *CreateEventJSONRequestBody
}

type CreateEventResponseObject interface {
	VisitCreateEventResponse(w http.ResponseWriter) error
}

type CreateEvent201JSONResponse EventIngestionResult

func (response CreateEvent201JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateEvent400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateEvent400JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateEvent422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CreateEvent422JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateEvent500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateEvent500JSONResponse) VisitCreateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEventRequestObject struct {
	Id ID `json:"id"`
}

type DeleteEventResponseObject interface {
	VisitDeleteEventResponse(w http.ResponseWriter) error
}

type DeleteEvent204Response struct {
}

func (response DeleteEvent204Response) VisitDeleteEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteEvent404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteEvent404JSONResponse) VisitDeleteEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteEvent500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteEvent500JSONResponse) VisitDeleteEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetEventRequestObject struct {
	Id ID `json:"id"`
}

type GetEventResponseObject interface {
	VisitGetEventResponse(w http.ResponseWriter) error
}

type GetEvent200JSONResponse Event

func (response GetEvent200JSONResponse) VisitGetEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEvent404JSONResponse struct{ NotFoundJSONResponse }

func (response GetEvent404JSONResponse) VisitGetEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetEvent500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetEvent500JSONResponse) VisitGetEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateEventRequestObject struct {
	Id   ID `json:"id"`
	Body *UpdateEventJSONRequestBody
}

type UpdateEventResponseObject interface {
	VisitUpdateEventResponse(w http.ResponseWriter) error
}

type UpdateEvent200JSONResponse Event

func (response UpdateEvent200JSONResponse) VisitUpdateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateEvent400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateEvent400JSONResponse) VisitUpdateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateEvent404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateEvent404JSONResponse) VisitUpdateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateEvent500JSONResponse struct{ InternalErrorJSONResponse }

func (response UpdateEvent500JSONResponse) VisitUpdateEventResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListRulesRequestObject struct {
	Params ListRulesParams
}

type ListRulesResponseObject interface {
	VisitListRulesResponse(w http.ResponseWriter) error
}

type ListRules200JSONResponse RuleList

func (response ListRules200JSONResponse) VisitListRulesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListRules500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListRules500JSONResponse) VisitListRulesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateRuleRequestObject struct {
	Body *CreateRuleJSONRequestBody
}

type CreateRuleResponseObject interface {
	VisitCreateRuleResponse(w http.ResponseWriter) error
}

type CreateRule201JSONResponse Rule

func (response CreateRule201JSONResponse) VisitCreateRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateRule400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateRule400JSONResponse) VisitCreateRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateRule422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CreateRule422JSONResponse) VisitCreateRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateRule500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateRule500JSONResponse) VisitCreateRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteRuleRequestObject struct {
	Id ID `json:"id"`
}

type DeleteRuleResponseObject interface {
	VisitDeleteRuleResponse(w http.ResponseWriter) error
}

type DeleteRule204Response struct {
}

func (response DeleteRule204Response) VisitDeleteRuleResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteRule404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteRule404JSONResponse) VisitDeleteRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteRule500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteRule500JSONResponse) VisitDeleteRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRuleRequestObject struct {
	Id ID `json:"id"`
}

type GetRuleResponseObject interface {
	VisitGetRuleResponse(w http.ResponseWriter) error
}

type GetRule200JSONResponse Rule

func (response GetRule200JSONResponse) VisitGetRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRule404JSONResponse struct{ NotFoundJSONResponse }

func (response GetRule404JSONResponse) VisitGetRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetRule500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetRule500JSONResponse) VisitGetRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateRuleRequestObject struct {
	Id   ID `json:"id"`
	Body *UpdateRuleJSONRequestBody
}

type UpdateRuleResponseObject interface {
	VisitUpdateRuleResponse(w http.ResponseWriter) error
}

type UpdateRule200JSONResponse Rule

func (response UpdateRule200JSONResponse) VisitUpdateRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateRule400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateRule400JSONResponse) VisitUpdateRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateRule404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateRule404JSONResponse) VisitUpdateRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateRule422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response UpdateRule422JSONResponse) VisitUpdateRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type UpdateRule500JSONResponse struct{ InternalErrorJSONResponse }

func (response UpdateRule500JSONResponse) VisitUpdateRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListTemplatesRequestObject struct {
	Params ListTemplatesParams
}

type ListTemplatesResponseObject interface {
	VisitListTemplatesResponse(w http.ResponseWriter) error
}

type ListTemplates200JSONResponse TemplateList

func (response ListTemplates200JSONResponse) VisitListTemplatesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTemplates500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListTemplates500JSONResponse) VisitListTemplatesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplateRequestObject struct {
	Body *CreateTemplateJSONRequestBody
}

type CreateTemplateResponseObject interface {
	VisitCreateTemplateResponse(w http.ResponseWriter) error
}

type CreateTemplate201JSONResponse Template

func (response CreateTemplate201JSONResponse) VisitCreateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplate400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateTemplate400JSONResponse) VisitCreateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplate422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CreateTemplate422JSONResponse) VisitCreateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplate500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateTemplate500JSONResponse) VisitCreateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTemplateRequestObject struct {
	Id ID `json:"id"`
}

type DeleteTemplateResponseObject interface {
	VisitDeleteTemplateResponse(w http.ResponseWriter) error
}

type DeleteTemplate204Response struct {
}

func (response DeleteTemplate204Response) VisitDeleteTemplateResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTemplate404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteTemplate404JSONResponse) VisitDeleteTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTemplate500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteTemplate500JSONResponse) VisitDeleteTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTemplateRequestObject struct {
	Id ID `json:"id"`
}

type GetTemplateResponseObject interface {
	VisitGetTemplateResponse(w http.ResponseWriter) error
}

type GetTemplate200JSONResponse Template

func (response GetTemplate200JSONResponse) VisitGetTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTemplate404JSONResponse struct{ NotFoundJSONResponse }

func (response GetTemplate404JSONResponse) VisitGetTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTemplate500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetTemplate500JSONResponse) VisitGetTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTemplateRequestObject struct {
	Id   ID `json:"id"`
	Body *UpdateTemplateJSONRequestBody
}

type UpdateTemplateResponseObject interface {
	VisitUpdateTemplateResponse(w http.ResponseWriter) error
}

type UpdateTemplate200JSONResponse Template

func (response UpdateTemplate200JSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTemplate400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateTemplate400JSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTemplate404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateTemplate404JSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTemplate422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response UpdateTemplate422JSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTemplate500JSONResponse struct{ InternalErrorJSONResponse }

func (response UpdateTemplate500JSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List events
	// (GET /events)
	ListEvents(ctx context.Context, request ListEventsRequestObject) (ListEventsResponseObject, error)
	// Ingest an event and evaluate active rules
	// (POST /events)
	CreateEvent(ctx context.Context, request CreateEventRequestObject) (CreateEventResponseObject, error)
	// Delete an event
	// (DELETE /events/{id})
	DeleteEvent(ctx context.Context, request DeleteEventRequestObject) (DeleteEventResponseObject, error)
	// Get an event by ID
	// (GET /events/{id})
	GetEvent(ctx context.Context, request GetEventRequestObject) (GetEventResponseObject, error)
	// Update an event
	// (PUT /events/{id})
	UpdateEvent(ctx context.Context, request UpdateEventRequestObject) (UpdateEventResponseObject, error)
	// List rules
	// (GET /rules)
	ListRules(ctx context.Context, request ListRulesRequestObject) (ListRulesResponseObject, error)
	// Create a rule (expression is validated before saving)
	// (POST /rules)
	CreateRule(ctx context.Context, request CreateRuleRequestObject) (CreateRuleResponseObject, error)
	// Delete a rule
	// (DELETE /rules/{id})
	DeleteRule(ctx context.Context, request DeleteRuleRequestObject) (DeleteRuleResponseObject, error)
	// Get a rule by ID
	// (GET /rules/{id})
	GetRule(ctx context.Context, request GetRuleRequestObject) (GetRuleResponseObject, error)
	// Update a rule (expression re-validated)
	// (PUT /rules/{id})
	UpdateRule(ctx context.Context, request UpdateRuleRequestObject) (UpdateRuleResponseObject, error)
	// List templates
	// (GET /templates)
	ListTemplates(ctx context.Context, request ListTemplatesRequestObject) (ListTemplatesResponseObject, error)
	// Create a template
	// (POST /templates)
	CreateTemplate(ctx context.Context, request CreateTemplateRequestObject) (CreateTemplateResponseObject, error)
	// Delete a template
	// (DELETE /templates/{id})
	DeleteTemplate(ctx context.Context, request DeleteTemplateRequestObject) (DeleteTemplateResponseObject, error)
	// Get a template by ID
	// (GET /templates/{id})
	GetTemplate(ctx context.Context, request GetTemplateRequestObject) (GetTemplateResponseObject, error)
	// Update a template
	// (PUT /templates/{id})
	UpdateTemplate(ctx context.Context, request UpdateTemplateRequestObject) (UpdateTemplateResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListEvents operation middleware
func (sh *strictHandler) ListEvents(ctx echo.Context, params ListEventsParams) error {
	var request ListEventsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListEvents(ctx.Request().Context(), request.(ListEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEvents")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListEventsResponseObject); ok {
		return validResponse.VisitListEventsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateEvent operation middleware
func (sh *strictHandler) CreateEvent(ctx echo.Context) error {
	var request CreateEventRequestObject

	var body CreateEventJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEvent(ctx.Request().Context(), request.(CreateEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateEventResponseObject); ok {
		return validResponse.VisitCreateEventResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteEvent operation middleware
func (sh *strictHandler) DeleteEvent(ctx echo.Context, id ID) error {
	var request DeleteEventRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteEvent(ctx.Request().Context(), request.(DeleteEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteEventResponseObject); ok {
		return validResponse.VisitDeleteEventResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetEvent operation middleware
func (sh *strictHandler) GetEvent(ctx echo.Context, id ID) error {
	var request GetEventRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetEvent(ctx.Request().Context(), request.(GetEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetEventResponseObject); ok {
		return validResponse.VisitGetEventResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateEvent operation middleware
func (sh *strictHandler) UpdateEvent(ctx echo.Context, id ID) error {
	var request UpdateEventRequestObject

	request.Id = id

	var body UpdateEventJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateEvent(ctx.Request().Context(), request.(UpdateEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateEventResponseObject); ok {
		return validResponse.VisitUpdateEventResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListRules operation middleware
func (sh *strictHandler) ListRules(ctx echo.Context, params ListRulesParams) error {
	var request ListRulesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListRules(ctx.Request().Context(), request.(ListRulesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRules")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListRulesResponseObject); ok {
		return validResponse.VisitListRulesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateRule operation middleware
func (sh *strictHandler) CreateRule(ctx echo.Context) error {
	var request CreateRuleRequestObject

	var body CreateRuleJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRule(ctx.Request().Context(), request.(CreateRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRule")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateRuleResponseObject); ok {
		return validResponse.VisitCreateRuleResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteRule operation middleware
func (sh *strictHandler) DeleteRule(ctx echo.Context, id ID) error {
	var request DeleteRuleRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteRule(ctx.Request().Context(), request.(DeleteRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteRule")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteRuleResponseObject); ok {
		return validResponse.VisitDeleteRuleResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetRule operation middleware
func (sh *strictHandler) GetRule(ctx echo.Context, id ID) error {
	var request GetRuleRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetRule(ctx.Request().Context(), request.(GetRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRule")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetRuleResponseObject); ok {
		return validResponse.VisitGetRuleResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateRule operation middleware
func (sh *strictHandler) UpdateRule(ctx echo.Context, id ID) error {
	var request UpdateRuleRequestObject

	request.Id = id

	var body UpdateRuleJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateRule(ctx.Request().Context(), request.(UpdateRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateRule")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateRuleResponseObject); ok {
		return validResponse.VisitUpdateRuleResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListTemplates operation middleware
func (sh *strictHandler) ListTemplates(ctx echo.Context, params ListTemplatesParams) error {
	var request ListTemplatesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListTemplates(ctx.Request().Context(), request.(ListTemplatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTemplates")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListTemplatesResponseObject); ok {
		return validResponse.VisitListTemplatesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateTemplate operation middleware
func (sh *strictHandler) CreateTemplate(ctx echo.Context) error {
	var request CreateTemplateRequestObject

	var body CreateTemplateJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTemplate(ctx.Request().Context(), request.(CreateTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateTemplateResponseObject); ok {
		return validResponse.VisitCreateTemplateResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteTemplate operation middleware
func (sh *strictHandler) DeleteTemplate(ctx echo.Context, id ID) error {
	var request DeleteTemplateRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTemplate(ctx.Request().Context(), request.(DeleteTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteTemplateResponseObject); ok {
		return validResponse.VisitDeleteTemplateResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTemplate operation middleware
func (sh *strictHandler) GetTemplate(ctx echo.Context, id ID) error {
	var request GetTemplateRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTemplate(ctx.Request().Context(), request.(GetTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTemplateResponseObject); ok {
		return validResponse.VisitGetTemplateResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateTemplate operation middleware
func (sh *strictHandler) UpdateTemplate(ctx echo.Context, id ID) error {
	var request UpdateTemplateRequestObject

	request.Id = id

	var body UpdateTemplateJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTemplate(ctx.Request().Context(), request.(UpdateTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateTemplateResponseObject); ok {
		return validResponse.VisitUpdateTemplateResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
